[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","I","B","UP","Q","RUF"]
ignore = ["E203","E501"]

# ← 全角カッコの警告は app.py と scripts/init_db.py だけ無視
[tool.ruff.lint.per-file-ignores]
"app.py" = ["RUF001","RUF003"]
"scripts/init_db.py" = ["RUF001","RUF003"]
