name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug env
        run: |
          which python || true
          python -V
          pip --version
          pip install -U pip
          pip install ruff
          python -c "import sys; print('ruff import ok'); import ruff; print('ruff', ruff.__version__)"

      - name: Ruff (lint)
        run: python -m ruff check . --output-format=github
      - name: Ruff (format check)
        run: python -m ruff format --check . --diff

  lint-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug env
        shell: pwsh
        run: |
          Get-Command python
          python -V
          pip --version
          python -m pip install -U pip
          pip install ruff
          python - << 'PY'
            import sys
            print("ruff import ok")
            import ruff
            print("ruff", ruff.__version__)
            PY

                  - name: Ruff (lint)
                    shell: pwsh
                    run: python -m ruff check . --output-format=github
                  - name: Ruff (format check)
                    shell: pwsh
                    run: python -m ruff format --check . --diff
