name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps (posix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python -m pip install -U pip
          pip install ruff black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Install deps (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pip install -U pip
          pip install ruff black
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }

      - name: Ruff
        run: ruff check .

      - name: Black (check)
        run: black --check .

      - name: Pytest (if present)
        if: hashFiles('tests/**') != ''
        shell: pwsh
        run: |
          pip install pytest
          pytest -q
