name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: |
          python -m pip install -U pip
          pip install ruff
      - name: Ruff (lint)
        run: ruff check . --output-format=github
      - name: Ruff (format check)
        run: ruff format --check . --diff

  lint-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        shell: pwsh
        run: |
          python -m pip install -U pip
          pip install ruff
      - name: Ruff (lint)
        shell: pwsh
        run: ruff check . --output-format=github
      - name: Ruff (format check)
        shell: pwsh
        run: ruff format --check . --diff
