name: Release (Windows)
on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build exe (bundle Qt + resources)
        shell: pwsh
        run: |
          $opts = @(
            "--noconfirm",
            "-F","app.py",
            "-n","DateNest",
            "--noconsole",
            # 隴幢ｽｪ闖ｴ・ｿ騾包ｽｨ邵ｺ・ｮ鬩･髦ｪ・樒ｹ晢ｽ｢郢ｧ・ｸ郢晢ｽ･郢晢ｽｼ郢晢ｽｫ郢ｧ蟶晏求陞溘・            "--exclude-module","PySide6.QtWebEngineCore",
            "--exclude-module","PySide6.QtWebEngineWidgets",
            "--exclude-module","PySide6.QtWebChannel",
            "--exclude-module","PySide6.QtQml",
            "--exclude-module","PySide6.QtQuick"
          )
          # 郢晢ｽｪ郢ｧ・ｽ郢晢ｽｼ郢ｧ・ｹ邵ｺ謔滂ｽｿ繝ｻ・ｦ竏壺・郢ｧ蟲ｨ笆｡邵ｺ螟ｧ驟碑ｭｴ・ｱ
          if (Test-Path ui)   { $opts += @("--add-data","ui;ui") }
          if (Test-Path data) { $opts += @("--add-data","data;data") }
          pyinstaller @opts
