name: Release (Windows)
on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}   #  これが「Run workflow」ボタンの鍵

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - name: Install deps
      shell: pwsh
      run: |
        python -m pip install -U pip
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        elseif (Test-Path pyproject.toml) { pip install . }
        else { pip install PySide6 }
        pip install -U pyinstaller pyinstaller-hooks-contrib

    - name: Build exe
      shell: pwsh
      run: |
        pyinstaller -F app.py -n DateNest `
          --collect-all PySide6 `
          --add-data "ui;ui" `
          --add-data "data;data"
