name: Release (Windows)
on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 萓晏ｭ倥・繧､繝ｳ繧ｹ繝医・繝ｫ・・yInstaller 繧堤｢ｺ螳溘↓蜈･繧後ｋ・・      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }
          elseif (Test-Path pyproject.toml) { python -m pip install . }
          else { python -m pip install PySide6 }
          python -m pip install -U pyinstaller pyinstaller-hooks-contrib
          python - << 'PY'
import sys
import PyInstaller, PySide6
print("Python:", sys.version)
print("PyInstaller:", PyInstaller.__version__)
print("PySide6:", PySide6.__version__)
PY

      # 繝薙Ν繝会ｼ・t 縺ｮ驥阪＞繝｢繧ｸ繝･繝ｼ繝ｫ縺ｯ髯､螟悶＠縺ｦ繧ｹ繝ｪ繝蛹厄ｼ・      - name: Build exe (bundle Qt + resources)
        shell: pwsh
        run: |
          $opts = @(
            "--noconfirm",
            "-F","app.py",
            "-n","DateNest",
            "--noconsole",
            "--exclude-module","PySide6.QtWebEngineCore",
            "--exclude-module","PySide6.QtWebEngineWidgets",
            "--exclude-module","PySide6.QtWebEngineQuick",
            "--exclude-module","PySide6.QtWebChannel",
            "--exclude-module","PySide6.QtQml",
            "--exclude-module","PySide6.QtQuick",
            "--exclude-module","PySide6.QtQuickControls2",
            "--exclude-module","PySide6.QtCharts",
            "--exclude-module","PySide6.QtPdf",
            "--exclude-module","PySide6.QtNetworkAuth",
            "--exclude-module","PySide6.QtPositioning"
          )
          if (Test-Path ui)   { $opts += @("--add-data","ui;ui") }
          if (Test-Path data) { $opts += @("--add-data","data;data") }
          python -m PyInstaller @opts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DateNest-win
          path: dist/DateNest.exe
          if-no-files-found: error
