name: Release (Windows)
on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          elseif (Test-Path pyproject.toml) { pip install . }
          else { pip install PySide6 }
          pip install -U pyinstaller pyinstaller-hooks-contrib

      - name: Build exe (bundle Qt + resources)
        shell: pwsh
        run: |
          $opts = @("--noconfirm","-F","app.py","-n","DateNest","--collect-all","PySide6")
          if (Test-Path ui)   { $opts += @("--add-data","ui;ui") }
          if (Test-Path data) { $opts += @("--add-data","data;data") }
          pyinstaller @opts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DateNest-win
          path: dist/DateNest.exe
